version: 2.1
 
jobs:
  lint-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install and Run Hadolint
          command: |
            sudo apt-get update
            sudo apt-get -y install hadolint
            hadolint Dockerfile
 
  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Login to GitHub Container Registry
          command: echo "$GITHUB_TOKEN" | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
      - run:
          name: Build and Push images to Github Packages
          command: |
             sudo mkdir /build &&
             docker build -t ghcr.io/amrilhakimsihotang/a433-microservices/amril2023/karsajobs:latest . &&
             docker push ghcr.io/amrilhakimsihotang/a433-microservices/amril2023/karsajobs:latest

workflows:
  version: 2
  karsajobs-ui-ci:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui
