version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install and Run Hadolint
          command: |
            sudo apt-get update
            sudo apt-get -y install hadolint
            hadolint Dockerfile

  test-app:
    docker:
      - image: golang:1.17
    steps:
      - checkout
      - run:
          name: Set up Go and Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Login to GitHub Container Registry
          command: docker login ghcr.io -u Jastiadirizal -p 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
      - run:
          name: Build and Push images to Github Packages
          command: |
            docker build -t ghcr.io/jastiadirizal/karsajobs:latest .
            docker push ghcr.io/jastiadirizal/karsajobs:latest

workflows:
  version: 2
  karsajobs-ci:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs:
          requires:
            - test-app
